#ordination_mat
DOWNLOAD: False
METHOD: "max"
THREADS: 10
ORDPATH: "ordination/"
DOWNLOAD_DIR: "downloads/"
COLLECTION_ID: 333
NS_MIN: 1
NS_MAX: 120000

#metadata
METAPATH: "metadata/"

#pca
SUBSET: "none"
NORM_ORDER: "rowcol"
ROW_METHOD: "sum"
ROW_TRANSFORM: "none"
COL_METHOD: "center"
COL_TRANSFORM: "power3"
COMPONENTS: 4
LOADINGS: 50
PLOT: True
HUE: "Species group"
STYLE: "Tissue"
PCAPATH: "pca/"

#lda
LDAPATH : "lda/"
LDALABEL: "Species group"

#sudat
SUSDAT: "Compound name"
CACHE: True
SUSPATH: "susdat/"
