#ordination_mat
DOWNLOAD: False
METHOD: "max"
THREADS: 10
ORDPATH: "ordination/"
DOWNLOAD_DIR: "downloads/"
COLLECTION_ID: 333
NS_MIN: 1
NS_MAX: 120000

#metadata
METAPATH: "metadata/"

#data processing 
SUBSET: "Instrument setup used"

#random seed
SEED: 3289

#plotting
PLOT: True
HUE: "Instrument setup used"
STYLE: "Species group"
LEGEND_BBOX_X: 0.7
LEGEND_BBOX_Y: -0.2

#pca
NORM_ORDER: "rowcol"
ROW_METHOD: "sum"
ROW_TRANSFORM: "none"
COL_METHOD: "center"
COL_TRANSFORM: "power3"
COMPONENTS: 2
LOADINGS: 50
PCAPATH: "pca/"

#lda
LDAPATH : "lda/"
LDALABEL: "Species group"

#sudat
SUSDAT: False
CACHE: True
SUSPATH: "susdat/"

#kmeans
KMEANS_PATH: "kmeans/"
KMEANS_P: 0.4
KMEANS_CLUSTERS: 2

#upset
UPSET_PATH: "upset/"
GROUPING: "ID"
MAX_SUBSET_RANK: 10 
MIN_SUBSET_SIZE: False
