#ordination_mat
DOWNLOAD: False
METHOD: 'max'
THREADS: 10
ORDPATH: "ordination/"
DOWNLOAD_DIR: "downloads/"
COLLECTION_ID: 333
NS_MIN: 1
NS_MAX: 120000

#metadata
METAPATH: "metadata/"

#pca
NORM_METHOD: "sum"
NORM_TRANSFORM: "power3"
COMPONENTS: 4
LOADINGS: 10
PLOT: True
HUE: 'Instrument setup used'
STYLE: 'Species group'
PCAPATH: "pca/"
