#ordination_mat
DOWNLOAD: False
METHOD: "max"
THREADS: 10
ORDPATH: "ordination/"
DOWNLOAD_DIR: "downloads/"
COLLECTION_ID: 333
NS_MIN: 1
NS_MAX: 120000

#metadata
METAPATH: "metadata/"

#pca
SUBSET: "Instrument setup used"
NORM_METHOD: "sum"
NORM_TRANSFORM: "power3"
COMPONENTS: 4
LOADINGS: 50
PLOT: True
HUE: "Species group"
STYLE: "Tissue"
PCAPATH: "pca/"

#sudat
SUSDAT: "Compound name"
CACHE: True
SUSPATH: "susdat/"
